In [7]:
#미분 numerical derivative

def my_func1(x):
    return x**2

def numerical_derivative(f, x): #f는 미분하려는 함수, 외부에서 def, lambda 등으로 정의됨
    delta_x = 1e-4 #lim에 해당되는 작은 값
    return (f(x+delta_x) - f(x-delta_x)) / (2*delta_x)

result = numerical_derivative(my_func1, 3)

print("result == ", result)

result ==  6.000000000012662


In [10]:
import numpy as np

def my_func1(x):
    return x**2

def my_func2(x):
    
    return 3*x*(np.exp(x))

def numerical_derivative(f, x):
    delta_x = 1e-4
    return (f(x+delta_x) - f(x-delta_x)) / (2*delta_x)

result = numerical_derivative(my_func2, 2)

print("result == ", result)

result ==  66.50150507518049


In [20]:
#다변수 함수에서의 편미분

import numpy as np

def numerical_derivative(f, x): #x는 모든 변수를 포함하고 있는 numpy객체(배열, 행렬...)
    delta_x = 1e-4
    grad = np.zeros_like(x) #x와 같은 형태인 행렬을 만들어 낸다. 단, 원소는 0
    # # zeros_like() 은 기존 img 배열의 shape과 dtype에서 동일한 값을 갖지만, 해당 배열의 값은 모두 '0'으로 생성된다. 
    # 새롭게 생성된 배열 b 의 shape이 기존의 parameter x의 shape 과 동일하다는 사실을 확인할 수 있다.
    
    it = np.nditer(x, flags = ['multi_index'], op_flags=['readwrite']) #모든 입력변수에 대해 편미분하기 위해 iterator 사용
    while not it.finished: 
        idx = it.multi_index
        
        tmp_val = x[idx] # numpy 타입은 mutable이므로 원래 값 보관
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad




In [23]:
import numpy as np

# 입력변수 1개인 함수 f(x) = x**2

def func1(input_obj):
    x = input_obj[0]
    
    return x**2

def numerical_derivative(f, x): #x는 모든 변수를 포함하고 있는 numpy객체(배열, 행렬...)
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. inital input variable =", x)
    print("debug 2. initial grad =", grad)
    print("======================================")
    
    it = np.nditer(x, flags = ['multi_index'], op_flags=['readwrite']) #모든 입력변수에 대해 편미분하기 위해 iterator 사용
    
    while not it.finished: 
        idx = it.multi_index
        
        print("debug 3. idx=", idx, ", x[idx]=", x[idx])
        
        tmp_val = x[idx] 
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4, grad[idx] =", grad[idx])
        print("debug 5, grad = ", grad)
        print("====================================")
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad



# x = 3에서의 편미분 값
numerical_derivative(func1, np.array([3.0]))

debug 1. inital input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx= (0,) , x[idx]= 3.0
debug 4, grad[idx] = 6.000000000012662
debug 5, grad =  [6.]


array([6.])

In [24]:
#다변수 함수

import numpy as np

def func1(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    
    return (2*x + 3*x*y + np.power(y,3))

def numerical_derivative(f, x): #x는 모든 변수를 포함하고 있는 numpy객체(배열, 행렬...)
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. inital input variable =", x)
    print("debug 2. initial grad =", grad)
    print("======================================")
    
    it = np.nditer(x, flags = ['multi_index'], op_flags=['readwrite']) #모든 입력변수에 대해 편미분하기 위해 iterator 사용
    
    while not it.finished: 
        idx = it.multi_index
        
        print("debug 3. idx=", idx, ", x[idx]=", x[idx])
        
        tmp_val = x[idx] 
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4, grad[idx] =", grad[idx])
        print("debug 5, grad = ", grad)
        print("====================================")
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad



# (x, y) = (1.0, 2.0) 에서의 편미분 값

input = np.array([1.0, 2.0])
numerical_derivative(func1, input)


debug 1. inital input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx= (0,) , x[idx]= 1.0
debug 4, grad[idx] = 7.999999999990237
debug 5, grad =  [8. 0.]
debug 3. idx= (1,) , x[idx]= 2.0
debug 4, grad[idx] = 15.000000010019221
debug 5, grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [28]:
#입력변수 4개인 함수
#f(w, x, y, z) = wx + xyz + 3w + zy^2
#input_obj는 행렬

def func1(input_obj):
    
    w = input_obj[0, 0] #input_obj의 1행1열 원소가 w
    x = input_obj[0, 1]
    y = input_obj[1, 0]
    z = input_obj[1, 1]
    
    return(w*x + x*y*z + 3*w + z*np.power(y, 2))

def numerical_derivative(f, x): #x는 모든 변수를 포함하고 있는 numpy객체(배열, 행렬...)
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. inital input variable =", x)
    print("debug 2. initial grad =", grad)
    print("======================================")
    
    it = np.nditer(x, flags = ['multi_index'], op_flags=['readwrite']) #모든 입력변수에 대해 편미분하기 위해 iterator 사용
    
    while not it.finished: 
        idx = it.multi_index
        
        print("debug 3. idx=", idx, ", x[idx]=", x[idx])
        
        tmp_val = x[idx] 
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4, grad[idx] =", grad[idx])
        print("debug 5, grad = ", grad)
        print("====================================")
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

#입력을 2x2 행렬로 구성함
input = np.array([[1.0, 2.0], [3.0, 4.0]])

numerical_derivative(func1, input)

debug 1. inital input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx= (0, 0) , x[idx]= 1.0
debug 4, grad[idx] = 5.000000000023874
debug 5, grad =  [[5. 0.]
 [0. 0.]]
debug 3. idx= (0, 1) , x[idx]= 2.0
debug 4, grad[idx] = 13.00000000000523
debug 5, grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx= (1, 0) , x[idx]= 3.0
debug 4, grad[idx] = 32.00000000006753
debug 5, grad =  [[ 5. 13.]
 [32.  0.]]
debug 3. idx= (1, 1) , x[idx]= 4.0
debug 4, grad[idx] = 15.000000000000568
debug 5, grad =  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])